export const commonStrings = {
  betdilla: 'Betdilla',
  yes: 'Yes',
  no: 'No',
  cancel: 'Cancel',
  ok: 'OK',
  submit: 'Submit',
  proceed: 'Proceed',
  smallAnd: 'and',
  loading: 'Loading Data',
  noResults: 'There are no results matching your search criteria.',
  logOut: 'Log Out',
  logIn: 'Log In',
  companySlogan: 'Bets, Never Regrets ',
  bannerSecondary: 'Login now to see our list of Games',
  temperature: temperature => `${Math.round(temperature)}°C`,
  uv: uv => `UV Index: ${Math.round(uv)}`,
};
