export const commonStrings = {
  betdilla: 'Betdilla',
  yes: 'Yes',
  no: 'No',
  cancel: 'Cancel',
  ok: 'OK',
  submit: 'Submit',
  proceed: 'Proceed',
  saveChanges: 'Save changes',
  remove: 'Remove',
  smallAnd: 'and',
  loading: 'Loading Data',
  noResults: 'There are no results matching your search criteria.',
  logOut: 'Log Out',
  logIn: 'Log In',
  amount: 'Amount',
  description: 'Description',
  username: 'Username',
  email: 'Email Address',
  password: 'Password',
  oldCheck: 'By enabling this switch I confirm that I am 18 years of age or older',
  companySlogan: 'Bets, Never Regrets ',
  bannerSecondary: 'Login now to see our list of Games',
  welcomeUsername: username => `Welcome, '${username}!'`,
  temperature: temperature => `${Math.round(temperature)}°C`,
  uv: uv => `UV Index: ${Math.round(uv)}`,
};
